title: "Harvard Mathematics Departmental Group"
description: "A departmental group in the Harvard University Mathematics Department, fostering mathematical community and collaboration."
baseurl: ""
url: "https://szhang612.github.io"

nav:
  - title: "Home"
    url: "/hggms/"
  - title: "About"
    url: "/hggms/about/"
  - title: "Schedule"
    url: "/hggms/schedule/"
  - title: "Members"
    url: "/hggms/members/"

theme: null
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
